### ISSUE TITLE
RuntimeError: Cannot run the event loop while another loop is running

### ISSUE THREAD

**Issue by ienjreny** [oliver006/elasticsearch-test-data#22]
I got the following error when I run the command

`python es_test_data.py --es_url=http://localhost:9200 --index_name=test`

**The error:**
[I 200622 08:48:49 es_test_data:52] Trying to create index http://localhost:9200/test
Traceback (most recent call last):
  File "es_test_data.py", line 281, in <module>
    tornado.ioloop.IOLoop.instance().run_sync(generate_test_data)
  File "C:\Program Files (x86)\Python\Python38-32\lib\site-packages\tornado\ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "C:\Program Files (x86)\Python\Python38-32\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "es_test_data.py", line 199, in generate_test_data
    create_index(tornado.options.options.index_name)
  File "es_test_data.py", line 54, in create_index
    response = tornado.httpclient.HTTPClient().fetch(request)
  File "C:\Program Files (x86)\Python\Python38-32\lib\site-packages\tornado\httpclient.py", line 107, in __init__
    self._async_client = self._io_loop.run_sync(make_client)
  File "C:\Program Files (x86)\Python\Python38-32\lib\site-packages\tornado\ioloop.py", line 526, in run_sync
    self.start()
  File "C:\Program Files (x86)\Python\Python38-32\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "C:\Program Files (x86)\Python\Python38-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Program Files (x86)\Python\Python38-32\lib\asyncio\base_events.py", line 560, in run_forever
    self._check_running()
  File "C:\Program Files (x86)\Python\Python38-32\lib\asyncio\base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running

**Comment by faudebert** [comment]
Just in case someone comes here: you need to use `tornado` version specified in `requirements.txt`. That is:

```sh
$ pip install -r requirements.txt
```
