### ISSUE TITLE
generate failed

### ISSUE THREAD

**Issue by fabianlv** [oliver006/elasticsearch-test-data#34]
[root@es01 elasticsearch-test-data-master]# python es_test_data.py --es_url=http://10.10.1.63:39201 --username=elastic --password=elastic --count=10000 --num_of_shards=5 --num_of_replicas=2 --batch_size=1000 --index_name=index03
[I 220905 21:34:08 es_test_data:56] Trying to create index http://10.10.1.63:39201/index03
Traceback (most recent call last):
  File "es_test_data.py", line 319, in <module>
    tornado.ioloop.IOLoop.instance().run_sync(generate_test_data)
  File "/usr/local/lib64/python3.6/site-packages/tornado/ioloop.py", line 530, in run_sync
    return future_cell[0].result()
  File "/usr/lib64/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 162, in _fake_ctx_run
    return f(*args, **kw)
  File "es_test_data.py", line 215, in generate_test_data
    create_index(tornado.options.options.index_name)
  File "es_test_data.py", line 58, in create_index
    response = tornado.httpclient.HTTPClient().fetch(request)
  File "/usr/local/lib64/python3.6/site-packages/tornado/httpclient.py", line 135, in fetch
    functools.partial(self._async_client.fetch, request, **kwargs)
AttributeError: 'Task' object has no attribute 'fetch'
Exception ignored in: <bound method HTTPClient.__del__ of <tornado.httpclient.HTTPClient object at 0x7f82db854160>>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/httpclient.py", line 113, in __del__
  File "/usr/local/lib64/python3.6/site-packages/tornado/httpclient.py", line 118, in close
AttributeError: 'Task' object has no attribute 'close'

**Comment by runkecheng** [comment]
same issue

**Comment by runkecheng** [comment]
upgrade python to 3.9, it works
